#!/usr/bin/env bash
set -e
cd "$(dirname "$0")"

BRANCH="iso-report-patch"
BASE="main"
TITLE="[Report] ISO Domain Dispute Cases"

echo "→ تحديث main من upstream"
git checkout "$BASE"
git pull origin "$BASE" 2>/dev/null || true

echo "→ توليد التقرير"
mkdir -p data
{
  echo "# ISO Domain Dispute Cases — Generated $(date -u +%F)"
  echo ""
  echo "Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "Source: WIPO UDRP case index"
  echo ""
  echo "## Summary"
  echo "- Total cases: $(grep -c '"case"' data/iso-domain-cases.json)"
} > report.md

echo "→ التبديل للفرع"
if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  git checkout "$BRANCH"
  git merge "$BASE" --no-edit || true
else
  git checkout -b "$BRANCH"
fi

echo "→ Commit"
git add -A
if git diff --cached --quiet; then
  echo "  لا تغييرات"
  exit 0
fi
git commit -m "[create-pull-request] automated change"

echo "→ Push"
git push -u origin "$BRANCH" --force

echo "→ إنشاء PR إن لم يكن موجودًا"
if ! gh pr view "$BRANCH" >/dev/null 2>&1; then
  gh pr create --base "$BASE" --head "$BRANCH" \
    --title "$TITLE" \
    --body "Auto-generated by cpr.sh" \
    --label "report" --label "iso" --label "automated pr"
else
  echo "  PR موجود مسبقًا — تم التحديث"
fi

echo "✓ انتهى"
